### PR TITLE
Added function insertBatch to insert multiple values

### PR DESCRIPTION
**Pull request by subhashdasyam**
Added function insertBatch to insert multiple values

### CODE REVIEW

**Comment by Zetaphor** [comment]
At first glance this looks good overall. Could you please clean up the merge conflict on the README? 

Also, and I'm not sure if this is me being nitpicky, but adding your name to the credit header in simplemysql.py seems unnecessary. I have write access on this repo and my name isn't in there, and neither is the name of any other contributors. I'm open to discussion on this, as I'm not sure what the de-facto standard is for this situation.

**Comment by subhashdasyam** [comment]
Ahh I am sorry, that was my local copy which i uploaded, i keep track of files with my name, i will understand for which i have contributed. 
I will remove the name from simplemysql

**Comment by subhashdasyam** [comment]
Can some one merge this issue.

**Comment by Zetaphor** [comment]
Merge complete, thank you for this contribution! Next time please make sure your fork is up to date with master so we don't keep having to resolve these README conflicts ;-)

**Pull request merged**
